/* eslint-disable max-len */
const modelDescriptions = {
  pldesc: `
  The Plackett-Luce model is a classical model of statistical ranking which has already been applied to study ranked choice voting in Ireland. Let's suppose the support for Candidate A from a voting group is twice the support for Candidate B. Under the Plackett-Luce model, we take this to mean that a voter is twice as likely to put Candidate A first as to put Candidate B first. In fact, the model assumes that this trend goes all the way down the ballot. That is, if a voter has not ranked either A or B yet on their ballot, then they are still twice as likely to write down Candidate A's name than Candidate B when they get to the next rank. See Critchlow, D.E., Fligner, M.A. and Verducci, J.S., 1991. Probability models on rankings. Journal of mathematical psychology, 35(3), pp.294-318 for mathematical details. It is unrealistic to expect the support for each class of candidates to be completely uniform, so to divide up the total support among candidates of a given class, we sample from a symmetric Dirichlet distribution. The Dirichlet distribution has one parameter (called concentration) which can be used to choose between mostly even division of support (concentration >> 1), and support concentrated on just a few candidates (concentration << 1). The default concentration value of 1.0 makes every division of the support equally likely, roughly speaking. We therefore refer to this parameter asevenness of support in the Model input tab.
  `,
  btdesc: `
  The paired comparison model is based on the idea that what matters in a ranking is who is preferred over whom. Suppose the support by a voting group for Candidate A is a and the support for Candidate B is b. This the model sets the probability that a voter in the group ranks Candidate A above Candidate B at a/(a+b). The probability of a full ranking is just the product of the probabilities associated with the order of each pair of candidates, with a normalizing constant so that everything sums to one. See  See Critchlow, D.E., Fligner, M.A. and Verducci, J.S., 1991. Probability models on rankings. Journal of mathematical psychology, 35(3), pp.294-318 for mathematical details. As with the Plackett-Luce model, we use a Dirichlet sampler to divide up the support among the candidates. The Dirichlet distribution has one parameter (called concentration) which can be used to choose between mostly even division of support (concentration >> 1), and support concentrated on just a few candidates (concentration << 1). The default concentration value of 1.0 makes every division of the support equally likely, roughly speaking. We therefore refer to this parameter asevenness of support in the Model input tab.
  `,
  acdesc: `
  This model posits that there are two kinds of voters in each group: block voters and crossover voters. Block voters always vote for ingroup candidates first and then outgroup candidates. Crossover voters alternate between the two classes of candidates, starting with an outgroup candidate (hence the name). This only tells you the type of candidate at each position in a ballot, however, so further choices are necessary to determine the exact order. For each group of voters and group of candidates, we allow two choices: random ordering by each voter, or consistent ordering by each voter. This model has been used in previous analyses of ranked voting by the MGGG at Tufts University (cf. MGGG, Election Reform in Lowell MA, https://mggg.org/lowell or MGGG, Analysis of county commission elections in Yakima County WA, https://mggg.org/uploads/yakima.pdf)
  `,
  csdesc: `
  Each voter's first choice under this model is the same as under alternating crossover, i.e. an ingroup candidate for block voters and an outgroup candidate for crossover voters. However, instead of allowing only a block ballot or alternating ballot, the types of candidates in the rest of the ballot are determined by sampling from the ballots in a decade's worth of Cambridge MA ranked choice city council elections. Once the type of candidate (ingroup or outgroup) at each rank has been chosen, random ordering or consistent ordering is applied to fill in the ballot with candidate names just as with the alternating crossover model.
  `,
};

module.exports = modelDescriptions;
